# Generated by Django 3.1 on 2023-07-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='account_paid',
            new_name='amount_paid',
        ),
    ]
